In [1]:
import torch

In [ ]:
torch_scalar = torch.tensor(3.14) # A scalar tensor
torch_scalar

tensor(3.1400)

In [5]:
torch_vector = torch.tensor([2, 4, 6, 8])
print(torch_vector) # A vector tensor

tensor([2, 4, 6, 8])


In [6]:
torch_matrix = torch.tensor([[12, 14],[16, 18],[20, 22],[24, 26]]) # 2D matrix tensor

print(torch_matrix) # A matrix tensor

tensor([[12, 14],
        [16, 18],
        [20, 22],
        [24, 26]])


In [9]:
torch_tensor3d = torch.tensor([[[0, 2, 4],
                                [6, 8, 10],],
                                [
                                    [12, 14, 16],
                                [18, 20, 22],
                                ],
                                [
                                    [24, 26, 28],
                                 [30, 32, 34],
                                 ],
                                 [
                                     [36, 38, 40],
                                 [42, 44, 46],
                                 ]
                                 ]) # 3D tensor

print(torch_tensor3d) # A 3D tensor

tensor([[[ 0,  2,  4],
         [ 6,  8, 10]],

        [[12, 14, 16],
         [18, 20, 22]],

        [[24, 26, 28],
         [30, 32, 34]],

        [[36, 38, 40],
         [42, 44, 46]]])


In [10]:
print(torch_tensor3d.shape)

torch.Size([4, 2, 3])


In [11]:
import numpy as np
import torch

# Create a random NumPy array
x_np = np.random.random((3, 5))  # 3 rows, 5 columns
print(x_np)
# Example output (values will be random):
# [[0.56347291 0.17683452 0.84931799 0.94718427 0.26507189]
#  [0.04859423 0.35608158 0.91547634 0.70918372 0.12945809]
#  [0.31789047 0.93812456 0.25783918 0.15896174 0.79729465]]

# Convert the NumPy array to a PyTorch tensor
x_pt = torch.tensor(x_np)
print(x_pt)
# Example output (values will be random):
# tensor([[0.5635, 0.1768, 0.8493, 0.9472, 0.2651],
#         [0.0486, 0.3561, 0.9155, 0.7092, 0.1295],
#         [0.3179, 0.9381, 0.2578, 0.1590, 0.7973]], dtype=torch.float64)

[[0.82467713 0.82293648 0.36871067 0.32399462 0.45503352]
 [0.50602184 0.75604264 0.05875321 0.53357969 0.18709218]
 [0.5581018  0.63834105 0.80935675 0.35702525 0.94816296]]
tensor([[0.8247, 0.8229, 0.3687, 0.3240, 0.4550],
        [0.5060, 0.7560, 0.0588, 0.5336, 0.1871],
        [0.5581, 0.6383, 0.8094, 0.3570, 0.9482]], dtype=torch.float64)


In [14]:
print(torch_tensor3d.dtype)

torch.int64


In [17]:
print(x_np.dtype, x_pt.dtype) 


x_np = np.asarray(x_np, dtype=np.float32)     
x_pt = torch.tensor(x_np, dtype=torch.float32) 
print(x_np.dtype, x_pt.dtype) 

float64 torch.float64
float32 torch.float32


In [19]:
# Masking Operations
b_np = x_np > 0.5
print(b_np)
print(b_np.dtype)

[[ True  True False False False]
 [ True  True False  True False]
 [ True  True  True False  True]]
bool


In [20]:
b_pt = x_pt > 0.5
print(b_pt)
print(b_pt.dtype)

tensor([[ True,  True, False, False, False],
        [ True,  True, False,  True, False],
        [ True,  True,  True, False,  True]])
torch.bool


In [ ]:
# Common pytorch functions
import torch

# Create a tensor
x = torch.tensor([[1., 2., 3.],[4., 5., 6.,]
                 ])  
# Check the data type of the tensor
print(x.dtype)

torch.float32


In [25]:
# 1. Indexing and slicing
print(x[0]) # first row
print(x[:, 1]) # second column

tensor([1., 2., 3.])
tensor([2., 5.])


In [26]:
# Tensor Creation
zeros = torch.zeros((2,3)) # Create a tensor filled with zeros
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
ones = torch.ones((4, 6)) # Create a tensor filled with ones
print(ones)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
